### PR TITLE
missing console classes

### PR DESCRIPTION
**Pull request by digitaldan**
Signed-off-by: Dan Cunningham <dan@digitaldan.com>

### CODE REVIEW

**Comment by digitaldan** [comment]
Apparently i missed checking these in.

**Comment by digitaldan** [comment]
BTW, you may be thinking why the console beeper commands are useful.  If you have ever had your system start beeping the consoles crazy loud, and non stop, this is the command that would stop them ( i think, i have not been home to confirm yet).  

Since I'm planning on using mostly android wall mounted tables for controls, this allows me to be able to cancel the indefinite beeps on the actual consoles.

**Comment by craigham** [comment]
Within the Omnilink I programmatically disable console beeps during the typical morning exit times for the sleepers, so i see value.

**Comment by craigham** [comment]
Dan, have you found a tablet which can turn on via presence detection when approaching?

**Comment by digitaldan** [comment]
I use android tables (4 nexus 2011 and 2 2013) running daydream mode, this dims the screen to the point where it's almost off and displays a clock.  I actually like this better then off as when the room is dark, you can just see the tablet and the time.   I then use a app call fully kiosk mode (or something) to put the habpanel ui into full screen mode.  This app actually does have a wake on presence, using the camera to detect motion, but I don't use it as daydream is a much better option imho.   I have a great keypad widget for the omni for habpanel, I'll try and post some screenshots.

**Comment by digitaldan** [comment]
I will look at the conflicts this weekend

**Comment by craigham** [comment]
@digitaldan I believe I have merged these PRs, just want to you double check the latest version of the branch to confirm.  Then we can close the PRs.

**Comment by digitaldan** [comment]
Ahh, ok thanks.  I was going a little crazy when trying to figure out the merge conflicts!  I will close these!

**Pull request closed without merging**
