### PR TITLE
Decoupled area mode from command channels. We now validate a user cod…

### PR DESCRIPTION
**Pull request by digitaldan**
…e and use it to arm/disarm

Signed-off-by: Dan Cunningham <dan@digitaldan.com>

### CODE REVIEW

**Comment by digitaldan** [comment]
so with these changes my items file looks like

`Number 		AlarmMode				"Alarm [MAP(area-modes.map):%s]" 			{channel="omnilink:area:1:mode"}`
`String 		AlarmModeDisarm			{channel="omnilink:area:1:disarm"}`
`String 		AlarmModeDay			{channel="omnilink:area:1:day"}`
`String 		AlarmModeNight			{channel="omnilink:area:1:night"}`
`String 		AlarmModeAway			{channel="omnilink:area:1:away"}`
`String 		AlarmModeVacation		{channel="omnilink:area:1:vacation"}`
`String 		AlarmModeDayInstant		{channel="omnilink:area:1:day_instant"}`
`String 		AlarmModeNightDelayed	{channel="omnilink:area:1:night_delayed"}`

To activate a channel you send your 4 digit code.  The system will validate it and perform the command. I could also add a generic command channel that would accept something like code:mode ( 1234:0) if needed to make this more convenient for sitemaps. 

This relates to issue #9 , @boc-tothefuture  thoughts?

**Comment by boc-tothefuture** [comment]
Looks good to me - this code right now is not actually doing the differentiation between 'arming' and  actual mode, correct?  It is just setting up the items/things?

**Comment by digitaldan** [comment]
>n 'arming' and actual mode, correct? 

That's actually already in this branch that the PR is against , if there is any exit delay we set the mode to one of the delayed types.

**Comment by digitaldan** [comment]
Code validation is always returning true right now, so I need to fix that

**Comment by digitaldan** [comment]
This is ready to merge

**Pull request merged**
