### PR TITLE
Completed work on ObjectPropertyRequests

### PR DESCRIPTION
**Pull request by boc-tothefuture**
This addresses #32

### CODE REVIEW

**Comment by craigham** [comment]
@boc-tothefuture 
When taking a look at the code, I had this idea, what do you think about using generics to return the specific Properties classes, instead of requiring the cast after?

I.e. , to builder add some method like return(Class class)

And call return(ButtonProperties.class) in the assembly?

**Comment by boc-tothefuture** [comment]
@craigham I agree, I am not a huge fan of casting.  Let me play around with a few different methods in the code and see what has the best feel.

**Comment by boc-tothefuture** [comment]
@craigham I added generic support and pushed.

**Comment by craigham** [comment]
Looks good @boc-tothefuture

**Pull request merged**
