### PR TITLE
Adds button trigger, removes state from button press

### PR DESCRIPTION
**Pull request by digitaldan**
[WIP] Button triggers

This is my  first attempt at using triggers.  I actually have not tried this out yet, I'll set something up tonight or tomorrow so I can actually test it.  A rule that could be activated from this might look like:

```java
rule "Button 1 Activated"
    when
        Channel "omnilink:button:home:1:activated" triggered
    then
        logInfo("TEST","Button/Macro 1 has been activated!");
end
```

wdyt?

### CODE REVIEW

**Comment by digitaldan** [comment]
So this indeed does work.

**Comment by craigham** [comment]
Dan, a little asleep at the wheel and I merged the PR after you said it
works...then I realized you had marked it as WIP so I should have confirmed
with you.

Sorry.

**Comment by digitaldan** [comment]
No worries, let me know if this works, both the trigger and the button not having any state (UnDef). 

Also I was thinking about the channel names, right now we have "press" and "activated".  Should this be "press" and "pressed", or should we have "activate" and "activated"

We also have other triggers that come directly from the "Other Event Notification" callback, these are 
 * X-10 / UPB / RadioRA signals are received
 * Certain trouble conditions are detected
 * The phone line changes state
 * The cost of energy changes
 * The user activates a macro button
 * Pro-Link message received
 * CentraLite switch is pressed
 * Camera trigger activated

Maybe we have a common naming pattern for these?  The button is a little different as we have a thing type and can associate the trigger with it, the others are probably channles associated with the bridge.  But triggers can have payloads, ie the value that the event has (x-10 code, area, UPB link number, etc...).  

So maybe xxxTrigger or xxxEvent ? So for example upbEvent, buttonEvent, cameraEvent, phoneLineDeadEvent, and so on.  Some will then carry a payload (number, area, etc...) and some will not (phone line events).  

@craigham and @boc-tothefuture wdyt?

**Comment by craigham** [comment]
Looks like it is working from my testing.

I could live with either of the naming suggestions you gave, and would also throw out toggle and toggled as choices.  I'd say whatever reads best in the rule usage, that is probably the most public exposure to the naming chosen.  Maybe that is Pressed?  

the whole event naming pattern looks well thought out as you have described.

**Comment by boc-tothefuture** [comment]
I like press and pressed.  For naming, I think the event naming scheme works. 

With this change, how does one trigger a button from a sitemap/item?

**Comment by craigham** [comment]
You could link an item to the press channel, I use switch.  Then your rules could work off the pressed channel getting triggered as shown above.

**Comment by digitaldan** [comment]
>With this change, how does one trigger a button from a sitemap/item?

As @craigham  mentioned, you need to still link a Switch item to the button "press" channel.  Note the this channel does not directly relate with the event trigger (pressed channel), it simply sends the button command to the omni.  The trigger is executed only when the omni activates the macro (from that button press, or from a keypad, mobile access, etc...) 

I'll work out some of the eventChannles and submit a PR for us to review.  Question, do we want to associate the button event with a button thing?  This seem logical, but will be an outlier as other "events" will just associated with the bridge.  If we keep it consistent, then all events would be channels on the bridge, including a single buttonEvent (which caries the button number as a payload)

**Comment by craigham** [comment]
@digitaldan Are you suggesting dynamically creating channels for the bridge for each button which is detected on the omnilink?  I have seen something like this before on another controller which had its variables right to the bridge...just want to make sure I understand.  Or are you thinking 1 channel for the buttons...and if that how would the rules figure out the button # pressed?

**Comment by digitaldan** [comment]
>Are you suggesting dynamically creating channels for the bridge for each button which is detected on the omnilink?

No, just one channel per event

>and if that how would the rules figure out the button # pressed?

If I modify the rule above it would look like:
```java
rule "Button Event"
    when
        Channel "omnilink:controller:home:1:buttonEvent" triggered
    then
        logInfo("TEST"," Button Triggered, # " + receivedEvent.event);
end
```

You should also be able to filter on the payload, so to just react to button 1, :
```java
rule "Button 1 Event"
    when
        Channel "omnilink:controller:home:1:buttonEvent" triggered  "1"
    then
        logInfo("TEST","Button/Macro 1 has been activated!");
end
```

**Comment by craigham** [comment]
how would we create items for button 1 and 2 in the items file?  switch wouldn't work if it had to specify a button # would it ?

**Comment by digitaldan** [comment]
This would not touch the existing button/press functionality, that would still be a channel on the button thing, and would have a item associated with it.  Triggers channels do not have links to items and can only be used in rules.

**Comment by boc-tothefuture** [comment]
Ok.  I think I got it.   Makes sense to me.  I am in the process of dogfooding our version so will see how it plays out during implementation.

**Pull request merged**
