### PR TITLE
Thermostat Support

### LINKED ISSUE #6: Thermostat support is missing from the V2 driver

### PR DESCRIPTION
**Pull request by boc-tothefuture**
This closes #6 

I have merged in @digitaldan's stuff for console beeping.

### CODE REVIEW

**Comment by digitaldan** [comment]
@boc-tothefuture should this PR be against the digitaldan-omnilink-binding-thing-types branch instead of master?  I think git should be smart enough that if we merge that first, and then this branch should merge ok, but it would probably be easier to review if this was not based of of master.

**Comment by digitaldan** [comment]
Also, I'm on the last day of my vacation, which is why I have not been able to review/contribute as frequently as I would like to :-)

**Comment by boc-tothefuture** [comment]
Thanks @digitaldan.  I changed the branch now..  but it only shows the latest file change..  I am guessing because my branch was merged and then backed out.  @craigham how should we resolve this?

**Comment by digitaldan** [comment]
Sorry I am getting all my branches mixed up, and I forgot we had merged the branch back into omnilink (and not master).  I'm not sure what the issue is, I have terrible internet right now and am having trouble checking out to take a closer look, my first instinct is to revert back to your changes, fetch the omnilink branch upstream and merge, but until I check out the branch its hard for me to know.

**Comment by digitaldan** [comment]
So I did a checkout out your branch, did a `git merge origin/omnilink-binding` where origin=https://github.com/QuailAutomation.  A PR based on this shows only your changes.

**Comment by boc-tothefuture** [comment]
@craigham said we were still merging against your branch.

**Comment by digitaldan** [comment]
@boc-tothefuture apologies, I was trying to help from my mobile, and on the run and realized I still had our branches confused.  I just got a few minutes back at my laptop.  Trying to figure out whats going on right now.

**Comment by digitaldan** [comment]
So I'm not 100% sure what the issue is, but in this case i would reset your branch, so in the "thermostat" branch run the command `git reset quail/digitaldan-omnilink-binding-thing-types` where quail is the name you gave this remote repo.  This will reset your changes against the correct branch.  Then do a `git add ./` in the org.openhab.binding.omnilink directory and a `git commit -as` to finally commit it again.  If this works, i would then force push it back up to your repo.  I would also have a local copy just in case things go sideways :-)

**Comment by craigham** [comment]
Brian,

Let me know if you get it to work with Dan's suggestion.  If you can't get it to work I can take a stab at it from here.

**Comment by craigham** [comment]
And sorry for messing it up by merging that PR.

**Comment by boc-tothefuture** [comment]
Ok @craigham.  I am away from my computer until tomorrow.  If you want to give it a shot go for it.  Otherwise I will try tomorrow.

**Comment by craigham** [comment]
I believe this will keep all the commit history.  It just deletes that last commit I did reverting your PR, so it gets in the state of applying your PR, then we can add the updated jomnilink jar and should be good.  Then we can apply those other PRs and be up to date.

I wouldn't do this in your working git, maybe clone the repos again somewhere else, and switch to the branch we are working on.  Or I could do it as well.

git clone https://github.com/QuailAutomation/openhab2-addons
git checkout origin/digitaldan-omnilink-binding-thing-types

Now this will reset so that we are back to the commit right after merging your PR

git reset --hard dc9d93c9bc460180fa4af54a59117ee661e901fd

Now you can add the updated omnilink jar and it should build.

You can confirm with git log that all the commits are still there.

Then we can apply those other PRs.

@digitaldan  @boc-tothefuture  does this look correct to you guys?

**Comment by digitaldan** [comment]
I know some really awesome git experts, unfortunately, I'm not one of them :-)  If undoing the last commit does the trick then that sounds good.

**Comment by boc-tothefuture** [comment]
@craigham I did the git reset --hard and then pushed to my branch again (force push was necessary.  When I look at the PR and even when I create a new PR I see the same thing.  The only file it notes that is changing is the omnilink.  However, when I look at my fork/branch that I am performing the PR from all my changes are still there.

**Comment by craigham** [comment]
I am working on it right now as well.

I have pushed the rewind so the latest on my Github should exclude my
revert of your PR.  Just need to add the updated jomilink lib.

The problem i have now is I think I need to rebase both of Dan's changes to
exclude that original reversion if that makes sense.  I had read about the
problems of removing a commit which may have been pulled...and now
experiencing it.

**Comment by boc-tothefuture** [comment]
@craigham OK - I see the thermostat handler back in this branch. Great work!  Do we just need to merge this one now back in w/ its updated jomnilink driver?

**Comment by craigham** [comment]
I think I need to rebase those other two PRs back 1 so they don't include
my revert and then all should be good again.

**Comment by boc-tothefuture** [comment]
Ok - @craigham - Just let us know when it is safe again?  I am holding off on any other changes until we are clear as I don't want to complicate things.

**Comment by craigham** [comment]
Ok, i think i have it working.  Warning ssh ing back to home from Spain and
merging via VI, so I may have missed something.  Could you guys get latest
of the branch and see if all is there you expect?

**Comment by boc-tothefuture** [comment]
This looks good to me.  It seems this PR can't be merged, so we close it?

**Pull request closed without merging**
